# Configuración de Dependabot para CreadorCraft-Classic-Backend
# Este archivo configura las actualizaciones automáticas de dependencias y seguridad

version: 2

updates:
  # Configuración para dependencias de npm/Node.js
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Mexico_City"
    open-pull-requests-limit: 5
    reviewers:
      - "Creadores-Program"
    assignees:
      - "Creadores-Program"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "automerge"
    # Permitir actualizaciones para diferentes tipos de versiones
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Ignorar actualizaciones específicas si es necesario
    ignore:
      # Ejemplo: ignorar actualizaciones major de una dependencia específica
      # - dependency-name: "package-name"
      #   update-types: ["version-update:semver-major"]
    
  # Configuración para GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "America/Mexico_City"
    open-pull-requests-limit: 2
    reviewers:
      - "Creadores-Program"
    assignees:
      - "Creadores-Program"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "ci/cd"

  # Configuración para dependencias de Docker (si se añaden en el futuro)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    reviewers:
      - "Creadores-Program"
    assignees:
      - "Creadores-Program"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "docker"
      - "dependencies"

# Configuración de alertas de seguridad
# Las alertas de seguridad están habilitadas por defecto y crearán PRs automáticamente
# para vulnerabilidades de seguridad conocidas en dependencias