name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: CreadorCraft-Maker
        uses: Creadores-Program/CreadorCraft-Maker-GHA@V1.2.0
        with:
          path: "./src"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CreadorCraft Classic
          path: gameBuildCCM/CreadorCraft Classic 1.0.0.creadorcraftgame.zip